const PRODUCT_TYPES = {
  FETCH_PRODUCTS_BY_SHOP_START: "FETCH_PRODUCTS_BY_SHOP_START",
  FETCH_PRODUCTS_SUCCESS: "FETCH_PRODUCTS_SUCCESS",
  FETCH_SHOPS_FAILURE: "FETCH_SHOPS_FAILURE",
};

export default PRODUCT_TYPES;
