const USER_TYPES = {
  CHECK_USER_SESSION: "CHECK_USER_SESSION",
  SIGN_IN_START: "SIGN_IN_START",
  SIGN_IN_SUCCESS: "SIGN_IN_SUCCESS",
  SIGN_IN_FAILURE: "SIGN_IN_FAILURE",
};

export default USER_TYPES;
